apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omamldata-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datasets-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: output-autokeras-claim
#   namespace: omaml
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: output-mljar-claim
#   namespace: omaml
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: output-autogluon-claim
#   namespace: omaml
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: output-autopytorch-claim
#   namespace: omaml
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: output-flaml-claim
#   namespace: omaml
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: output-autosklearn-claim
#   namespace: omaml
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: output-mcfly-claim
#   namespace: omaml
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: output-pycaret-claim
#   namespace: omaml
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisdata-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: output-evalml-claim
#   namespace: omaml
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: output-tpot-claim
#   namespace: omaml
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: output-gama-claim
#   namespace: omaml
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-lama-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-csi

