apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: autokeras
  name: autokeras
  namespace: omaml
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: autokeras
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: autokeras
    spec:
      containers:
      - env:
        - name: GRPC_SERVER_PORT
          value: "50052"
        - name: EXPLAINER_DASHBOARD_PORT_START
          value: "4000"
        - name: EXPLAINER_DASHBOARD_PORT_END
          value: "4010"
        image: alexhda/omaml-autokeras
        imagePullPolicy: ""
        name: autokeras
        resources:
          limits:
            cpu: "1.5"
            memory: "2097152e3"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: output-autokeras
          mountPath: /app/app-data/training
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: output-autokeras
        persistentVolumeClaim:
          claimName: output-autokeras-claim
