apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: blazorboilerplate
  name: blazorboilerplate
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blazorboilerplate
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: blazorboilerplate
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - cai-omaml-main
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: Admin123
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: aspnetapp.pfx
        - name: ASPNETCORE_URLS
          value: https://+:443;http://+80
        - name: BlazorBoilerplate__ApplicationUrl
          value: blazorboilerplate
        - name: BlazorBoilerplate__CertificatePassword
          value: Admin123
        - name: BlazorBoilerplate__UseSqlServer
          value: "true"
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver;Database=omaml;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourVeryStrong(!)Password;Integrated Security=false"
        - name: Serilog__MinimumLevel__Default
          value: Debug
        - name: CONTROLLER_DATASET_FOLDER_PATH
          value: /app/app-data/datasets
        - name: REGISTRATION_ALLOWED
          value: "false"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: training
          mountPath: /app/app-data/training
        - name: autokeras-output
          mountPath: /app/app-data/training/autokeras
        - name: mljar-output
          mountPath: /app/app-data/training/mljar
        - name: autocve-output
          mountPath: /app/app-data/training/autocve
        - name: gluon-output
          mountPath: /app/app-data/training/gluon
        - name: pytorch-output
          mountPath: /app/app-data/training/autopytorch
        - name: flaml-output
          mountPath: /app/app-data/training/flaml
        - name: sklearn-output
          mountPath: /app/app-data/training/autosklearn
        - name: mcfly-output
          mountPath: /app/app-data/training/mcfly
        image: alexhda/omaml-frontend:latest
        name: blazorboilerplate
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: "2"
            memory: "2194304e3"
      restartPolicy: Always
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: training
        persistentVolumeClaim:
          claimName: training-claim
      - name: autokeras-output
        persistentVolumeClaim:
          claimName: output-autokeras-claim
      - name: mljar-output
        persistentVolumeClaim:
          claimName: output-mljar-claim
      - name: autocve-output
        persistentVolumeClaim:
          claimName: output-autocve-claim
      - name: gluon-output
        persistentVolumeClaim:
          claimName: output-gluon-claim
      - name: pytorch-output
        persistentVolumeClaim:
          claimName: output-pytorch-claim
      - name: flaml-output
        persistentVolumeClaim:
          claimName: output-flaml-claim
      - name: sklearn-output
        persistentVolumeClaim:
          claimName: output-sklearn-claim
      - name: mcfly-output
        persistentVolumeClaim:
          claimName: output-mcfly-claim
status: {}