apiVersion: v1
kind: Service
metadata:
  namespace: omaml
  labels:
    io.kompose.service: redis
  name: redis
spec:
  type: ClusterIP
  ports:
  - name: "6379"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}