apiVersion: v1
kind: PersistentVolume
metadata:
  name: redisdata-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: "/redisdb"