# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Controller_pb2 as Controller__pb2


class ControllerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAutoMlModel = channel.unary_unary(
                '/ControllerService/GetAutoMlModel',
                request_serializer=Controller__pb2.GetAutoMlModelRequest.SerializeToString,
                response_deserializer=Controller__pb2.GetAutoMlModelResponse.FromString,
                )
        self.GetDatasets = channel.unary_unary(
                '/ControllerService/GetDatasets',
                request_serializer=Controller__pb2.GetDatasetsRequest.SerializeToString,
                response_deserializer=Controller__pb2.GetDatasetsResponse.FromString,
                )
        self.GetDataset = channel.unary_unary(
                '/ControllerService/GetDataset',
                request_serializer=Controller__pb2.GetDatasetRequest.SerializeToString,
                response_deserializer=Controller__pb2.GetDatasetResponse.FromString,
                )
        self.GetSessions = channel.unary_unary(
                '/ControllerService/GetSessions',
                request_serializer=Controller__pb2.GetSessionsRequest.SerializeToString,
                response_deserializer=Controller__pb2.GetSessionsResponse.FromString,
                )
        self.GetSessionStatus = channel.unary_unary(
                '/ControllerService/GetSessionStatus',
                request_serializer=Controller__pb2.GetSessionStatusRequest.SerializeToString,
                response_deserializer=Controller__pb2.GetSessionStatusResponse.FromString,
                )
        self.GetTabularDatasetColumnNames = channel.unary_unary(
                '/ControllerService/GetTabularDatasetColumnNames',
                request_serializer=Controller__pb2.GetTabularDatasetColumnNamesRequest.SerializeToString,
                response_deserializer=Controller__pb2.GetTabularDatasetColumnNamesResponse.FromString,
                )
        self.GetTasks = channel.unary_unary(
                '/ControllerService/GetTasks',
                request_serializer=Controller__pb2.GetTasksRequest.SerializeToString,
                response_deserializer=Controller__pb2.GetTasksResponse.FromString,
                )
        self.UploadDatasetFile = channel.unary_unary(
                '/ControllerService/UploadDatasetFile',
                request_serializer=Controller__pb2.UploadDatasetFileRequest.SerializeToString,
                response_deserializer=Controller__pb2.UploadDatasetFileResponse.FromString,
                )
        self.StartAutoMLprocess = channel.unary_unary(
                '/ControllerService/StartAutoMLprocess',
                request_serializer=Controller__pb2.StartAutoMLprocessRequest.SerializeToString,
                response_deserializer=Controller__pb2.StartAutoMLprocessResponse.FromString,
                )


class ControllerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAutoMlModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTabularDatasetColumnNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDatasetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartAutoMLprocess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAutoMlModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAutoMlModel,
                    request_deserializer=Controller__pb2.GetAutoMlModelRequest.FromString,
                    response_serializer=Controller__pb2.GetAutoMlModelResponse.SerializeToString,
            ),
            'GetDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatasets,
                    request_deserializer=Controller__pb2.GetDatasetsRequest.FromString,
                    response_serializer=Controller__pb2.GetDatasetsResponse.SerializeToString,
            ),
            'GetDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataset,
                    request_deserializer=Controller__pb2.GetDatasetRequest.FromString,
                    response_serializer=Controller__pb2.GetDatasetResponse.SerializeToString,
            ),
            'GetSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessions,
                    request_deserializer=Controller__pb2.GetSessionsRequest.FromString,
                    response_serializer=Controller__pb2.GetSessionsResponse.SerializeToString,
            ),
            'GetSessionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionStatus,
                    request_deserializer=Controller__pb2.GetSessionStatusRequest.FromString,
                    response_serializer=Controller__pb2.GetSessionStatusResponse.SerializeToString,
            ),
            'GetTabularDatasetColumnNames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTabularDatasetColumnNames,
                    request_deserializer=Controller__pb2.GetTabularDatasetColumnNamesRequest.FromString,
                    response_serializer=Controller__pb2.GetTabularDatasetColumnNamesResponse.SerializeToString,
            ),
            'GetTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTasks,
                    request_deserializer=Controller__pb2.GetTasksRequest.FromString,
                    response_serializer=Controller__pb2.GetTasksResponse.SerializeToString,
            ),
            'UploadDatasetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDatasetFile,
                    request_deserializer=Controller__pb2.UploadDatasetFileRequest.FromString,
                    response_serializer=Controller__pb2.UploadDatasetFileResponse.SerializeToString,
            ),
            'StartAutoMLprocess': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAutoMLprocess,
                    request_deserializer=Controller__pb2.StartAutoMLprocessRequest.FromString,
                    response_serializer=Controller__pb2.StartAutoMLprocessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ControllerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAutoMlModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ControllerService/GetAutoMlModel',
            Controller__pb2.GetAutoMlModelRequest.SerializeToString,
            Controller__pb2.GetAutoMlModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ControllerService/GetDatasets',
            Controller__pb2.GetDatasetsRequest.SerializeToString,
            Controller__pb2.GetDatasetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ControllerService/GetDataset',
            Controller__pb2.GetDatasetRequest.SerializeToString,
            Controller__pb2.GetDatasetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ControllerService/GetSessions',
            Controller__pb2.GetSessionsRequest.SerializeToString,
            Controller__pb2.GetSessionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ControllerService/GetSessionStatus',
            Controller__pb2.GetSessionStatusRequest.SerializeToString,
            Controller__pb2.GetSessionStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTabularDatasetColumnNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ControllerService/GetTabularDatasetColumnNames',
            Controller__pb2.GetTabularDatasetColumnNamesRequest.SerializeToString,
            Controller__pb2.GetTabularDatasetColumnNamesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ControllerService/GetTasks',
            Controller__pb2.GetTasksRequest.SerializeToString,
            Controller__pb2.GetTasksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadDatasetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ControllerService/UploadDatasetFile',
            Controller__pb2.UploadDatasetFileRequest.SerializeToString,
            Controller__pb2.UploadDatasetFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartAutoMLprocess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ControllerService/StartAutoMLprocess',
            Controller__pb2.StartAutoMLprocessRequest.SerializeToString,
            Controller__pb2.StartAutoMLprocessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
