# supplementary docker-compose file

services:
  blazorboilerplate:
    build:
      context: frontend
      # the below path is relative to the build context
      dockerfile: ./src/Utils/Docker/Dockerfile
    ports:
      - 54415:80
      - 54443:443
    depends_on:
      - sqlserver
      - controller
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Production #Consider changing this in Production
      - Serilog__MinimumLevel__Default=Debug #Consider changing this in Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=blazor_boilerplate;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourVeryStrong(!)Password;Integrated Security=false
      - BlazorBoilerplate__UseSqlServer=true
      - BlazorBoilerplate__ApplicationUrl=blazorboilerplate
      - BlazorBoilerplate__IS4ApplicationUrl=blazorboilerplate
      - BlazorBoilerplate__CertificatePassword=omaml2022Alex#
      - ASPNETCORE_URLS=https://+:443;http://+80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=omaml2022Alex#
      - ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetapp.pfx
      - CONTROLLER_SERVICE_HOST=controller
      - CONTROLLER_SERVICE_PORT=5001
      - REDIS_SERVICE_HOST=redis
      - REDIS_SERVICE_PORT=6379
      - CONTROLLER_DATASET_FOLDER_PATH=/app/app-data/datasets
    restart: on-failure
    volumes:
      # shared volumes between frontend and controller
      - datasets:/app/app-data/datasets
      - training:/app/app-data/training
    extra_hosts:
      - "docker.host.internal:host-gateway"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - dbdata:/var/opt/mssql
    environment:
      - SA_PASSWORD=yourVeryStrong(!)Password
      - ACCEPT_EULA=Y
    ports:
      - 1533:1433 #expose port, so can connect to it using host: 'localhost,1533' | user: sa, password: yourVeryStrong(!)Password

  redis:
    image: "redis:alpine"
    volumes:
      - redisdata:/data
      - redisdata:/var/lib/redis
      - redisdata:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

volumes:
  dbdata:
  redisdata: