apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: pycaret
  name: pycaret
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pycaret
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pycaret
    spec:
      containers:
      - env:
        - name: GRPC_SERVER_PORT
          value: "50063"
        image: alexhda/omaml-pycaret
        imagePullPolicy: ""
        name: pycaret
        resources:
          limits:
            cpu: "2"
            memory: "2097152e3"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: output-pycaret
          mountPath: /app/app-data/training
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: output-pycaret
        persistentVolumeClaim:
          claimName: output-pycaret-claim
