apiVersion: v1
kind: Service
metadata:
  namespace: omaml
  labels:
    io.kompose.service: chatbot
  name: chatbot
spec:
  type: ClusterIP
  ports:
  - name: "50051"
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    io.kompose.service: chatbot
status:
  loadBalancer: {}
