apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: omaml
  labels:
    io.kompose.service: chatbot
  name: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chatbot
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chatbot
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - oma-ml-1
      serviceAccountName: ""
      containers:
      - env:
        image: alexhda/omaml-chatbot
        imagePullPolicy: ""
        name: chatbot
        resources:
            requests:
                memory: "16Gi"
                cpu: "12"
            limits:
                memory: "16Gi"
                cpu: "12"
        volumeMounts:
      restartPolicy: Always
      volumes:
