apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: evalml
  name: evalml
  namespace: omaml
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: evalml
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: evalml
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - oma-ml-2
      containers:
      - env:
        - name: GRPC_SERVER_PORT
          value: "50062"
        - name: EXPLAINER_DASHBOARD_PORT_START
          value: "4000"
        - name: EXPLAINER_DASHBOARD_PORT_END
          value: "4010"
        - name: ADAPTER_NAME
          value: "evalml"
        - name: JOB_FILE_NAME
          value: "evaml-job.json"
        - name: GRPC_SERVER_ADDRESS
          value: "0.0.0.0"
        - name: EXPORT_ZIP_FILE_NAME
          value: "evaml-export"
        - name: TRAINING_PATH
          value: "app-data/training"
        - name: JOB_FOLDER_NAME
          value: "job"
        - name: MODEL_FOLDER_NAME
          value: "model"
        - name: EXPORT_FOLDER_NAME
          value: "export"
        - name: RESULT_FOLDER_NAME
          value: "result"
        - name: TEMPLATES_PATH
          value: "app-data/templates"
        - name: PREDICT_TIME_SOURCES_PATH
          value: "AutoMLs/predict_time_sources.py"
        - name: LOCAL_EXECUTION
          value: "NO"
        - name: RUNNING_IN_WSL
          value: "NO"
        - name: DASHBOARD_FOLDER_NAME
          value: "dashboard"
        - name: WSL_METAAUTOML_PATH
          value: "/mnt/c/Users/alex/Desktop/MetaAutoML"
        - name: ONTOLOGY_PATH
          value: "ML_Ontology.ttl"
        image: alexhda/omaml-evalml
        imagePullPolicy: ""
        name: evalml
        resources:
            requests:
                memory: "28Gi"
                cpu: "12"
            limits:
                memory: "28Gi"
                cpu: "12"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: output-evalml
          mountPath: /app/app-data/training
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: output-evalml
        persistentVolumeClaim:
          claimName: output-evalml-claim
