apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-pod-account
  namespace: omaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller-pod-account-role
  namespace: omaml
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-pod-account-role-binding
  namespace: omaml
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: controller-pod-account-role
subjects:
- kind: ServiceAccount
  name: controller-pod-account
  namespace: omaml
