apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: omaml
  labels:
    io.kompose.service: mongodbdata-pvc
  name: mongodbdata-pvc
spec:
  storageClassName: local
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
status: {}
