apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: omaml
  labels:
    io.kompose.service: redisdata-pvc
  name: redisdata-pvc
spec:
  storageClassName: local
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
status: {}
