apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: omaml
  labels:
    io.kompose.service: controller
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: controller
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: controller
    spec:
      containers:
      - env:
        - name: "MONGO_DB_DEBUG"
          value: "NO"
        - name: "MONGO_CLUSTER"
          value: "YES"
        image: alexhda/omaml-controller
        imagePullPolicy: ""
        name: controller
        resources:
          limits:
            cpu: "1"
            memory: "1097152e3"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: autokeras-output
          mountPath: /app/app-data/output/autokeras
        - name: mljar-output
          mountPath: /app/app-data/output/mljar
        - name: autocve-output
          mountPath: /app/app-data/output/autocve
        - name: gluon-output
          mountPath: /app/app-data/output/gluon
        - name: pytorch-output
          mountPath: /app/app-data/output/pytorch
        - name: flaml-output
          mountPath: /app/app-data/output/flaml
        - name: sklearn-output
          mountPath: /app/app-data/output/sklearn
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: autokeras-output
        persistentVolumeClaim:
          claimName: output-autokeras-claim
      - name: mljar-output
        persistentVolumeClaim:
          claimName: output-mljar-claim
      - name: autocve-output
        persistentVolumeClaim:
          claimName: output-autocve-claim
      - name: gluon-output
        persistentVolumeClaim:
          claimName: output-gluon-claim
      - name: pytorch-output
        persistentVolumeClaim:
          claimName: output-pytorch-claim
      - name: flaml-output
        persistentVolumeClaim:
          claimName: output-flaml-claim
      - name: sklearn-output
        persistentVolumeClaim:
          claimName: output-sklearn-claim
