apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: blazorboilerplate
  name: blazorboilerplate
  namespace: omaml
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    io.kompose.service: blazorboilerplate