# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AdapterService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x41\x64\x61pterService.proto\";\n\x12TestAdapterRequest\x12\x10\n\x08testData\x18\x01 \x01(\t\x12\x13\n\x0bprocessJson\x18\x02 \x01(\t\"Q\n\x13TestAdapterResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x16\n\x0epredictiontime\x18\x03 \x01(\x02\")\n\x12StartAutoMLRequest\x12\x13\n\x0bprocessJson\x18\x01 \x01(\t\"\xe2\x01\n\x19StartAutoMLStreamResponse\x12&\n\nreturnCode\x18\x01 \x01(\x0e\x32\x12.AdapterReturnCode\x12\x14\n\x0cstatusUpdate\x18\x02 \x01(\t\x12\x12\n\noutputJson\x18\x03 \x01(\t\x12\x11\n\ttestScore\x18\x04 \x01(\x02\x12\x17\n\x0fvalidationScore\x18\x05 \x01(\x02\x12\x0f\n\x07runtime\x18\x06 \x01(\x05\x12\x16\n\x0epredictiontime\x18\x07 \x01(\x02\x12\x0f\n\x07library\x18\x08 \x01(\t\x12\r\n\x05model\x18\t \x01(\t\"8\n\x13\x45xplainModelRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x13\n\x0bprocessJson\x18\x02 \x01(\t\"-\n\x14\x45xplainModelResponse\x12\x15\n\rprobabilities\x18\x01 \x01(\t*\x9b\x01\n\x11\x41\x64\x61pterReturnCode\x12\x1f\n\x1b\x41\x44\x41PTER_RETURN_CODE_UNKNOWN\x10\x00\x12\x1f\n\x1b\x41\x44\x41PTER_RETURN_CODE_SUCCESS\x10\x01\x12%\n!ADAPTER_RETURN_CODE_STATUS_UPDATE\x10\x02\x12\x1d\n\x19\x41\x44\x41PTER_RETURN_CODE_ERROR\x10\x64\x32\xd5\x01\n\x0e\x41\x64\x61pterService\x12H\n\x11StartAutoMLStream\x12\x13.StartAutoMLRequest\x1a\x1a.StartAutoMLStreamResponse\"\x00\x30\x01\x12:\n\x0bTestAdapter\x12\x13.TestAdapterRequest\x1a\x14.TestAdapterResponse\"\x00\x12=\n\x0c\x45xplainModel\x12\x14.ExplainModelRequest\x1a\x15.ExplainModelResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AdapterService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADAPTERRETURNCODE._serialized_start=546
  _ADAPTERRETURNCODE._serialized_end=701
  _TESTADAPTERREQUEST._serialized_start=24
  _TESTADAPTERREQUEST._serialized_end=83
  _TESTADAPTERRESPONSE._serialized_start=85
  _TESTADAPTERRESPONSE._serialized_end=166
  _STARTAUTOMLREQUEST._serialized_start=168
  _STARTAUTOMLREQUEST._serialized_end=209
  _STARTAUTOMLSTREAMRESPONSE._serialized_start=212
  _STARTAUTOMLSTREAMRESPONSE._serialized_end=438
  _EXPLAINMODELREQUEST._serialized_start=440
  _EXPLAINMODELREQUEST._serialized_end=496
  _EXPLAINMODELRESPONSE._serialized_start=498
  _EXPLAINMODELRESPONSE._serialized_end=543
  _ADAPTERSERVICE._serialized_start=704
  _ADAPTERSERVICE._serialized_end=917
# @@protoc_insertion_point(module_scope)
