apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tpot
  name: tpot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tpot
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tpot
    spec:
      containers:
      - env:
        - name: GRPC_SERVER_PORT
          value: "50052"
        image: alexhda/omaml-tpot
        imagePullPolicy: ""
        name: tpot
        resources:
          limits:
            cpu: "1"
            memory: "1097152e3"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: output-tpot
          mountPath: /app/app-data/training
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: output-tpot
        persistentVolumeClaim:
          claimName: output-tpot-claim
