apiVersion: v1
kind: Service
metadata:
  name: autokeras
spec:
  type: ClusterIP
  ports:
  - name: "50052"
    port: 50052
    protocol: TCP
    targetPort: 50052
  selector:
    io.kompose.service: autokeras
status:
  loadBalancer: {}