apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mcfly
  name: mcfly
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mcfly
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mcfly
    spec:
      containers:
      - env:
        - name: GRPC_SERVER_PORT
          value: "50054"
        image: alexhda/omaml-mcfly
        imagePullPolicy: ""
        name: mcfly
        resources:
          limits:
            cpu: "1"
            memory: "1097152e3"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: output-mcfly
          mountPath: /app/app-data/output
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: output-mcfly
        persistentVolumeClaim:
          claimName: output-mcfly-claim
