apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: alphad3m
  name: alphad3m
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alphad3m
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: alphad3m
    spec:
      containers:
      - env:
        - name: GRPC_SERVER_PORT
          value: "50052"
        image: alexhda/omaml-alphad3m
        imagePullPolicy: ""
        name: alphad3m
        resources:
          limits:
            cpu: "1"
            memory: "1097152e3"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: output-alphad3m
          mountPath: /app/app-data/output
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: output-alphad3m
        persistentVolumeClaim:
          claimName: output-alphad3m-claim
