apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mljar
  name: mljar
  namespace: omaml
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mljar
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mljar
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - oma-ml-3
      containers:
      - env:
        - name: GRPC_SERVER_PORT
          value: "50053"
        - name: EXPLAINER_DASHBOARD_PORT_START
          value: "4000"
        - name: EXPLAINER_DASHBOARD_PORT_END
          value: "4010"
        image: alexhda/omaml-mljar
        imagePullPolicy: ""
        name: mljar
        resources:
            requests:
                memory: "28Gi"
                cpu: "12"
            limits:
                memory: "28Gi"
                cpu: "12"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: output-mljar
          mountPath: /app/app-data/training
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: output-mljar
        persistentVolumeClaim:
          claimName: output-mljar-claim
