apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: evalml
  name: evalml
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: evalml
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: evalml
    spec:
      containers:
      - env:
        - name: GRPC_SERVER_PORT
          value: "50062"
        image: alexhda/omaml-evalml
        imagePullPolicy: ""
        name: evalml
        resources:
          limits:
            cpu: "1.5"
            memory: "2097152e3"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: output-evalml
          mountPath: /app/app-data/training
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: output-evalml
        persistentVolumeClaim:
          claimName: output-evalml-claim
