apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: lama
  name: lama
  namespace: omaml
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lama
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: lama
    spec:
      containers:
      - env:
        - name: GRPC_SERVER_PORT
          value: "50066"
        - name: EXPLAINER_DASHBOARD_PORT_START
          value: "4000"
        - name: EXPLAINER_DASHBOARD_PORT_END
          value: "4010"
        image: alexhda/omaml-lama
        imagePullPolicy: ""
        name: lama
        resources:
          limits:
            cpu: "2"
            memory: "2097152e3"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: output-lama
          mountPath: /app/app-data/training
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: output-lama
        persistentVolumeClaim:
          claimName: output-lama-claim
