apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: blazorboilerplate-node
  name: blazorboilerplate-node
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 80
    nodePort: 30778
  - protocol: TCP
    targetPort: 443
    nodePort: 30878
  selector:
    io.kompose.service: blazorboilerplate
status:
  loadBalancer: {}
