apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: omaml
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sqlserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: sqlserver
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - oma-ml-2
      containers:
      - env:
        - name: "ACCEPT_EULA"
          value: "Y"
        - name: "SA_PASSWORD"
          value: "yourVeryStrong(!)Password"
        image: mcr.microsoft.com/azure-sql-edge:latest
        imagePullPolicy: ""
        name: sqlserver
        ports:
        - containerPort: 1433
        resources:
            requests:
                memory: "2Gi"
                cpu: "0.5"
            limits:
                memory: "2Gi"
                cpu: "0.5"
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: dbdata
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: dbdata-claim
