apiVersion: v1
kind: Service
metadata:
  namespace: omaml
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  type: ClusterIP
  ports:
  - name: "27017"
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    io.kompose.service: mongodb
status:
  loadBalancer: {}
