# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Adapter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Adapter.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rAdapter.proto\";\n\x12TestAdapterRequest\x12\x10\n\x08testData\x18\x01 \x01(\t\x12\x13\n\x0bprocessJson\x18\x02 \x01(\t\"Q\n\x13TestAdapterResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x16\n\x0epredictiontime\x18\x03 \x01(\x02\")\n\x12StartAutoMLRequest\x12\x13\n\x0bprocessJson\x18\x01 \x01(\t\"\xdc\x01\n\x13StartAutoMLResponse\x12&\n\nreturnCode\x18\x01 \x01(\x0e\x32\x12.AdapterReturnCode\x12\x14\n\x0cstatusUpdate\x18\x02 \x01(\t\x12\x12\n\noutputJson\x18\x03 \x01(\t\x12\x11\n\ttestScore\x18\x04 \x01(\x02\x12\x17\n\x0fvalidationScore\x18\x05 \x01(\x02\x12\x0f\n\x07runtime\x18\x06 \x01(\x05\x12\x16\n\x0epredictiontime\x18\x07 \x01(\x02\x12\x0f\n\x07library\x18\x08 \x01(\t\x12\r\n\x05model\x18\t \x01(\t*\x9b\x01\n\x11\x41\x64\x61pterReturnCode\x12\x1f\n\x1b\x41\x44\x41PTER_RETURN_CODE_UNKNOWN\x10\x00\x12\x1f\n\x1b\x41\x44\x41PTER_RETURN_CODE_SUCCESS\x10\x01\x12%\n!ADAPTER_RETURN_CODE_STATUS_UPDATE\x10\x02\x12\x1d\n\x19\x41\x44\x41PTER_RETURN_CODE_ERROR\x10\x64\x32\x8a\x01\n\x0e\x41\x64\x61pterService\x12<\n\x0bStartAutoML\x12\x13.StartAutoMLRequest\x1a\x14.StartAutoMLResponse\"\x00\x30\x01\x12:\n\x0bTestAdapter\x12\x13.TestAdapterRequest\x1a\x14.TestAdapterResponse\"\x00\x62\x06proto3'
)

_ADAPTERRETURNCODE = _descriptor.EnumDescriptor(
  name='AdapterReturnCode',
  full_name='AdapterReturnCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADAPTER_RETURN_CODE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADAPTER_RETURN_CODE_SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADAPTER_RETURN_CODE_STATUS_UPDATE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADAPTER_RETURN_CODE_ERROR', index=3, number=100,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=428,
  serialized_end=583,
)
_sym_db.RegisterEnumDescriptor(_ADAPTERRETURNCODE)

AdapterReturnCode = enum_type_wrapper.EnumTypeWrapper(_ADAPTERRETURNCODE)
ADAPTER_RETURN_CODE_UNKNOWN = 0
ADAPTER_RETURN_CODE_SUCCESS = 1
ADAPTER_RETURN_CODE_STATUS_UPDATE = 2
ADAPTER_RETURN_CODE_ERROR = 100



_TESTADAPTERREQUEST = _descriptor.Descriptor(
  name='TestAdapterRequest',
  full_name='TestAdapterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='testData', full_name='TestAdapterRequest.testData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processJson', full_name='TestAdapterRequest.processJson', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=76,
)


_TESTADAPTERRESPONSE = _descriptor.Descriptor(
  name='TestAdapterResponse',
  full_name='TestAdapterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='predictions', full_name='TestAdapterResponse.predictions', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='TestAdapterResponse.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predictiontime', full_name='TestAdapterResponse.predictiontime', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=159,
)


_STARTAUTOMLREQUEST = _descriptor.Descriptor(
  name='StartAutoMLRequest',
  full_name='StartAutoMLRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='processJson', full_name='StartAutoMLRequest.processJson', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=202,
)


_STARTAUTOMLRESPONSE = _descriptor.Descriptor(
  name='StartAutoMLResponse',
  full_name='StartAutoMLResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='returnCode', full_name='StartAutoMLResponse.returnCode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='statusUpdate', full_name='StartAutoMLResponse.statusUpdate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outputJson', full_name='StartAutoMLResponse.outputJson', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='testScore', full_name='StartAutoMLResponse.testScore', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='validationScore', full_name='StartAutoMLResponse.validationScore', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='runtime', full_name='StartAutoMLResponse.runtime', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predictiontime', full_name='StartAutoMLResponse.predictiontime', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='library', full_name='StartAutoMLResponse.library', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='StartAutoMLResponse.model', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=425,
)

_STARTAUTOMLRESPONSE.fields_by_name['returnCode'].enum_type = _ADAPTERRETURNCODE
DESCRIPTOR.message_types_by_name['TestAdapterRequest'] = _TESTADAPTERREQUEST
DESCRIPTOR.message_types_by_name['TestAdapterResponse'] = _TESTADAPTERRESPONSE
DESCRIPTOR.message_types_by_name['StartAutoMLRequest'] = _STARTAUTOMLREQUEST
DESCRIPTOR.message_types_by_name['StartAutoMLResponse'] = _STARTAUTOMLRESPONSE
DESCRIPTOR.enum_types_by_name['AdapterReturnCode'] = _ADAPTERRETURNCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestAdapterRequest = _reflection.GeneratedProtocolMessageType('TestAdapterRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTADAPTERREQUEST,
  '__module__' : 'Adapter_pb2'
  # @@protoc_insertion_point(class_scope:TestAdapterRequest)
  })
_sym_db.RegisterMessage(TestAdapterRequest)

TestAdapterResponse = _reflection.GeneratedProtocolMessageType('TestAdapterResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTADAPTERRESPONSE,
  '__module__' : 'Adapter_pb2'
  # @@protoc_insertion_point(class_scope:TestAdapterResponse)
  })
_sym_db.RegisterMessage(TestAdapterResponse)

StartAutoMLRequest = _reflection.GeneratedProtocolMessageType('StartAutoMLRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTAUTOMLREQUEST,
  '__module__' : 'Adapter_pb2'
  # @@protoc_insertion_point(class_scope:StartAutoMLRequest)
  })
_sym_db.RegisterMessage(StartAutoMLRequest)

StartAutoMLResponse = _reflection.GeneratedProtocolMessageType('StartAutoMLResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTAUTOMLRESPONSE,
  '__module__' : 'Adapter_pb2'
  # @@protoc_insertion_point(class_scope:StartAutoMLResponse)
  })
_sym_db.RegisterMessage(StartAutoMLResponse)



_ADAPTERSERVICE = _descriptor.ServiceDescriptor(
  name='AdapterService',
  full_name='AdapterService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=586,
  serialized_end=724,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartAutoML',
    full_name='AdapterService.StartAutoML',
    index=0,
    containing_service=None,
    input_type=_STARTAUTOMLREQUEST,
    output_type=_STARTAUTOMLRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TestAdapter',
    full_name='AdapterService.TestAdapter',
    index=1,
    containing_service=None,
    input_type=_TESTADAPTERREQUEST,
    output_type=_TESTADAPTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADAPTERSERVICE)

DESCRIPTOR.services_by_name['AdapterService'] = _ADAPTERSERVICE

# @@protoc_insertion_point(module_scope)
