apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: h2o
  name: h2o
  namespace: omaml
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: h2o
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: h2o
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - oma-ml-1
      containers:
      - env:
        - name: GRPC_SERVER_PORT
          value: "50067"
        - name: EXPLAINER_DASHBOARD_PORT_START
          value: "4000"
        - name: EXPLAINER_DASHBOARD_PORT_END
          value: "4010"
        image: alexhda/omaml-h2o
        imagePullPolicy: ""
        name: h2o
        resources:
            requests:
                memory: "10Gi"
                cpu: "5"
            limits:
                memory: "10Gi"
                cpu: "5"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: output-h2o
          mountPath: /app/app-data/training
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: output-h2o
        persistentVolumeClaim:
          claimName: output-h2o-claim
